name: template
description: Flutter boilerplate project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons:

  hive:
  hive_flutter:
  intl:
  http:
  provider:
  auto_route:
  reflectable:
  path_provider:
  flutter_phoenix:
  permission_handler:
  dart_json_mapper_flutter:

  fluttertoast:
  adaptive_dialog:
  flutter_svg:
  flutter_svg_provider:
  cached_network_image:
  animate_do:

dev_dependencies:
  build_runner:
  auto_route_generator:
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: interBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: interRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
